version: "3.8"

services:
  app:
    container_name: lafinas
    image: lafinas-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
