FROM node:16-alpine as development
ENV NODE_ENV development

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .

#RUN yarn install
RUN npm i

# Copy app files
COPY . .

# Expose port
EXPOSE 5173

# Start the app
CMD [ "npm", "run", "dev" ]
